import HomeSvg from "../Assets/svg/Home.svg";
import chekout from "../Assets/svg/chekout.svg";
const Images = {
  HomeSvg,
  chekout,
  logndots: require("../Assets/Images/logndots.webp"),
  checkinout: require("../Assets/Images/checkinout.png"),
  hidden_eyes: require("../Assets/Images/hidden_eyes.png"),
  show_eyes: require("../Assets/Images/show_eyes.png"),
  next: require("../Assets/Images/Next.png"),
  white_BackIcon: require("../Assets/Images/white_BackIcon.png"),
  not_found: require("../Assets/Images/not_found.png"),
  backArrow: require("../Assets/Images/backArrow.png"),
  drawermenu: require("../Assets/Images/more.png"),
  home: require("../Assets/Images/home.png"),
  mycreation: require("../Assets/Images/mycreation.png"),
  privacy: require("../Assets/Images/privacy.png"),
  rate: require("../Assets/Images/rate.png"),
  share: require("../Assets/Images/share.png"),
  terms: require("../Assets/Images/terms.png"),
  banner: require("../Assets/Images/banner.png"),
  user: require("../Assets/Images/user.png"),
  applogo: require("../Assets/Images/applogo.png"),
  pass: require("../Assets/Images/pass.png"),
  draewuser: require("../Assets/Images/draewuser.png"),
  listimg1: require("../Assets/Images/listimg1.png"),
  listimg2: require("../Assets/Images/listimg2.png"),
  listimg3: require("../Assets/Images/listimg3.png"),
  listimg4: require("../Assets/Images/listimg4.png"),
  listimg5: require("../Assets/Images/listimg5.png"),
  blackbacicon: require("../Assets/Images/blackbacicon.png"),
  Delete: require("../Assets/Images/Delete.png"),
  Edit: require("../Assets/Images/Edit.png"),
  activeSetting: require("../Assets/Images/activeSetting.png"),
  Setting: require("../Assets/Images/Setting.png"),
  Filter: require("../Assets/Images/Filter.png"),
  cutomerimg: require("../Assets/Images/cutomerimg.png"),
  Call: require("../Assets/Images/Call.png"),
  calender: require("../Assets/Images/calender.png"),
  activehome: require("../Assets/Images/activehome.png"),
  drawerbackground: require("../Assets/Images/drawerbackground.png"),
  inactiveHome: require("../Assets/Images/inactiveHome.png"),
  Productcatalog: require("../Assets/Images/Productcatalog.png"),
  DrawerCustomer: require("../Assets/Images/DrawerCustomer.png"),
  LogOut: require("../Assets/Images/LogOut.png"),
  Order: require("../Assets/Images/Order.png"),
  catelogBanner: require("../Assets/Images/catelogBanner.png"),
  Orderstatus: require("../Assets/Images/Orderstatus.png"),
  Realtimelocationtrack: require("../Assets/Images/Realtimelocationtrack.png"),
  Attendance: require("../Assets/Images/Attendance.png"),
  draweruser: require("../Assets/Images/draweruser.png"),
  activeNotification: require("../Assets/Images/activeNotification.png"),
  camera: require("../Assets/Images/camera.png"),
  Plus: require("../Assets/Images/Plus.png"),
  email: require("../Assets/Images/email.png"),
  Location: require("../Assets/Images/Location.png"),
  callprofile: require("../Assets/Images/callprofile.png"),
  ordehistry: require("../Assets/Images/ordehistry.png"),
  Editwhite: require("../Assets/Images/Editwhite.png"),
  forwardArrow: require("../Assets/Images/forwardArrow.png"),
  Search: require("../Assets/Images/Search.png"),
  downig: require("../Assets/Images/downig.png"),
  crossicon: require("../Assets/Images/crossicon.png"),
  attendence: require("../Assets/Images/attendence.png"),
  inactiveNotification: require("../Assets/Images/inactiveNotification.png"),
  checkin: require("../Assets/Images/checkin.png"),
  noimg: require("../Assets/Images/noimg.jpeg"),
  pdf: require("../Assets/Images/pdf.webp")
};

export default Images;
