const Screen = {
  RootHome: "RootHome",
  HomeScreen: "HomeScreen",
  LoginScreen: "LoginScreen",
  SettingScreen: "SettingScreen",
  NotificationScreen: "NotificationScreen",
  CustomerScreen: "CustomerScreen",
  ProductCatalog: "ProductCatalog",
  Profile: "Profile",
  EditProfile: "EditProfile",
  OrderHistory: "OrderHistory",
  CatalogDetils: "CatalogDetils",
  OdooApiProxy: "OdooApiProxy",
  ShowOrderScreen: "ShowOrderScreen",
  NewCreateOrderScreen: "NewCreateOrderScreen",
  SellOrderDetails: "SellOrderDetails",
  LiveLocationScreen: "LiveLocationScreen",
  AttendanceHistoryScreen: "AttendanceHistoryScreen",
  Locationsendscreen: "Locationsendscreen",
  EditOrderLineScreen: "EditOrderLineScreen",
  PdfViewer: "pdfViewer",
  OrderFilterScreen: "OrderFilterScreen",
};

export default Screen;
